# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 075ce0998a92706604be4941256bd748d274a2f169d06abcda326f862ac9c17f2a2dc71a00bec58092744b45eab76a351daf393e3cc4725471c4b9ba708adb5b

test:
  secret_key_base: 3f3ca3ec7d223942be0fb401687ac9310aca7b28e68f988a510848c7902f81d01ab76a087cbe33579698015e1846c0879a869923a735bc160d38c59dc020b922

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
